---
title: "Health, Healing, and Hope (H3)"
tagline: "A journey of the peaks and valleys of health, healing, and hope."
description: "Join me as I catalog my journey of health, healing, and hope. Find paleo, gluten-free, refined sugar-free, and egg-free recipes along with wellness tips for your own health journey."
email: laura@h3withlaura.com
facebook_URL: "https://www.facebook.com/h3withlaura"
author: Laura Sanders
font-awesome-icon-logo: ~
github_username: ~
instagram_username: lauramsanders
logo-image-url: https://res.cloudinary.com/rockmonkey/image/upload/dpr_auto,f_auto,fl_any_format.fast_scale.force_strip.immutable_cache.progressive.progressive:semi.progressive:steep,q_auto/v1587782942/android-chrome-192x192_Logo_xkc9t6.png
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
future: false
timezone: America/Chicago

# SEO specific settings
seo:
  keywords: >-
    paleo recipes, gluten free recipes, health tips, refined sugar free, egg free recipes,
    healing journey, wellness, health blog, nutrition, whole foods, autoimmune, food sensitivities

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://h3withlaura.com"

# baseurl: "/rockmonkey4004" # the subpath of your site, e.g. /blog
# url: "https://h3withlaura.com" # the base hostname & protocol for your site

github: [metadata]

# Author and social settings - enhanced for better SEO
social:
  name: Laura Sanders
  links:
    - https://www.facebook.com/h3withlaura
    - https://www.instagram.com/lauramsanders/
  profiles:
    facebook: h3withlaura
    instagram: lauramsanders

# Facebook Open Graph
facebook:
  app_id: 2327305430910604
  publisher: 103500687925393
  admins:

# Twitter card settings
twitter:
  username: 
  card: summary_large_image

# Default image for social sharing and search results
defaults:
  - scope:
      path: ""
    values:
      image: https://res.cloudinary.com/rockmonkey/image/upload/v1587782937/Blog/Burger-Up-Salad_w1gncd.jpg
      author: Laura Sanders

# Schema.org structured data
schema:
  type: BlogPosting
  author:
    type: Person
    name: Laura Sanders
  publisher:
    type: Organization
    name: Health, Healing, and Hope (H3)
    logo:
      type: ImageObject
      url: https://res.cloudinary.com/rockmonkey/image/upload/dpr_auto,f_auto,fl_any_format.fast_scale.force_strip.immutable_cache.progressive.progressive:semi.progressive:steep,q_auto/v1587782942/android-chrome-192x192_Logo_xkc9t6.png

# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
# ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://h3withlaura.herokuapp.com/v2/entry/rockmonkey4004/rockmonkey4004.github.io/master/comments

reCaptcha:
  siteKey: 6LffZOcUAAAAAPuQDgsqg9V1vJQMcK9vaoA6ksXN
  secret: QGLuiCFT+Wm70+E+vz+D35E6DlaUKpl1z4U3cC/CN7lAgiL0pQaWGbifIiAwnaU30Twa2shWU4QwwGBd88i2YY8C6P7kPIdH3dONMwqPYZiuC9DpMNQUC0Vs2E/mVntPUq1J5ecRUzYiPmst2wAwM6vYwYrO55Pzmg/HpQB+o1rX0+F3mheof6QcPfyw2mI2Ka7B5jJ9MWwQpVNbp0wDHEQzHpYUx48QN+tl9DuPnDAoPjQbkXO+LsP1O4eh8jdFqkO6mo9RcbzRciVjzxkNQEAgayxh8efWB0GrNQfxl5464qidQTpiJVQDgYUjRGnmNjXEwU1M21j5Alo7rp/Rzjce4Ko8yKDNIcrGehFrv+1DbNvWYmFLdO2aNz7WpSPGDbXSGu6amkGSFfYKhtOVmvBI2rsPke6tvo6tSmiewfqdJlKB9BVvgxINGdzvbjwvfsCS0gsCzd7k/1re0iHvjwoC8RyHO0Glqif3UEUWT2gK2G1n23LcGYeBnHiyXHuvxh7hVRfex7SsMvC0MXNu2BLi95uzZs4J3bwYh1ASei+Y/7rPgEpJkDHYMnwiDBfkS+3AxdGYXF2mu3zq6eVVuRaM4Thpb47yY6W7V3Rh/LFd5pP8W3n4HFX2FqjoxrCe8egLvtEiC77bS43ciA5P2MRxufWrrl2027S2E9Re+0Q=

############################################################
# Algolia search - enhanced for better search capabilities
algolia:
  application_id: SFBKC3K3JE
  index_name: blog_posts # replace with the name of your index (index database)
  search_only_api_key: 85b2425c53e4d9a38ce774223eea053f
  files_to_exclude:
    - index.html
    - index.md
    - _layouts/blog.html
    - _layouts/default.html
  nodes_to_index: 'p,h1,h2,h3,h4,h5,h6,li'
  settings:
    searchableAttributes:
      - title
      - tags
      - html
      - content
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - p
      - li

############################################################

# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: 'en_US'

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################

#### Minifier - optimized for faster page loading
jekyll-minifier:
  preserve_php: false                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: false      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  uglifier_args:                    # Default: (empty)

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-last-modified-at
  - jekyll-minifier

# Google Analytics - Add your ID here if you have one
# google_analytics: UA-XXXXXXXX-X
